<?php

namespace Exo2\ToolBox;

class Point extends Figure
{
    private float $x;
    private float $y;

    public function __construct(string $color, string $name, float $x, float $y)
    {
        parent::__construct($color, $name);
        $this->x = $x;
        $this->y = $y;
    }

    public function __get(string $name)
    {
        return $this->$name;
    }

    public function __set(string $name, $value): void
    {
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function __toString(): string
    {
        $str = parent::__toString();
        $str .= "<h5>" . parent::getNameClass(self::class) . "</h5>";
        $str .= "<ul>";
        foreach (get_object_vars($this) as $key => $value) {
            if (is_array($value)) {
                $value = implode('___________________________ ', $value);
            }
            $str .= "<li>" . gettype($value) . " " . $key . " = " . $value . "</li>";
        }
        $str .= "</ul>";

        return $str;
    }
}